### PR TITLE
Successful Validation for All Current Opcodes

### LINKED ISSUE #11: Test RV32 base instruction and behavior verification
After validation of all RV32I instructions

### PR DESCRIPTION
**Pull request by shibcreate**
PR made to bring them onto the first revision as example codes for each current opcode.

### CODE REVIEW

**Review by pranjalchanda08 — COMMENTED** [review]
Hi @shibcreate, 
Can you please comment all the instructions so that readers can understand.

**Review by pranjalchanda08 — CHANGES_REQUESTED** [review]
We shall even add comment as what is expected post execution

**Comment by shibcreate** [comment]
Did you want me to comment on all the .s files? Or as a separate README

**Comment by pranjalchanda08** [comment]
> Did you want me to comment on all the .s files? Or as a separate README

I guess separate README would also be a good option

**Review by pranjalchanda08 — APPROVED** [review]
LGTM

**Pull request merged**
