### PR TITLE
jalr, store instruction bug fixes

### LINKED ISSUE #15: JALR does not output expected result
When running: 

```asm
.align 2

.section .text
.globl _start

_start: 
    la t0, function
    jalr ra, 0(t0)

function:
    li t1, 0x12345
    ret

.section .data
 ```

I get the output

`x0: 0x00000000
  ra: 0x0000100c
  sp: 0x00000000
  gp: 0x00000000
  tp: 0x00000000
  t0: 0x0000100c
  t1: 0x00000000
  t2: 0x00000000
  s0: 0x00000000
  s1: 0x00000000
  a0: 0x00000000
  a1: 0x00000000
  a2: 0x00000000
  a3: 0x00000000
  a4: 0x00000000
  a5: 0x00000000
  a6: 0x00000000
  a7: 0x00000000
  s2: 0x00000000
  s3: 0x00000000
  s4: 0x00000000
  s5: 0x00000000
  s6: 0x00000000
  s7: 0x00000000
  s8: 0x00000000
  s9: 0x00000000
 s10: 0x00000000
 s11: 0x00000000
  t3: 0x00000000
  t4: 0x00000000
  t5: 0x00000000
  t6: 0x00000000
  pc: 0x00002014
`

I want to verify if this is user error / expected / bug

### PR DESCRIPTION
**Pull request by pranjalchanda08**

### CODE REVIEW

**Review by shibcreate — CHANGES_REQUESTED** [review]
When I run the same code provided in the issues page, I get a infinite loop

image

**Comment by pranjalchanda08** [comment]
> When I run the same code provided in the issues page, I get a infinite loop
> 

```asm
.align 2

.section .text
.globl _start

function:
    li t1, 0x12345
    ret

_start:
    la t0, function
    jalr ra, 0(t0)

.section .data
```

The loop was caused due to incorrect asm code

```sh
-------------- Execution Start --------------

[0x00000297]: [PC:0x0000100C]: auipc    t0, 0x0
[0xFF428293]: [PC:0x00001010]: addi     t0, t0, 0xfffffff4
[0x000280E7]: [PC:0x00001014]: jalr     ra, 0x0(t0)
[0x00012337]: [PC:0x00001000]: lui      t1, 0x12000
[0x34530313]: [PC:0x00001004]: addi     t1, t1, 0x345
[0x00008067]: [PC:0x00001008]: jalr     x0, 0x0(ra)
[0x00000000]: [PC:0x00001018]: PC reached EOF
-------------- Execution End ----------------
```

**Review by shibcreate — APPROVED** [review]

**Comment by pranjalchanda08** [comment]
closes #15

**Comment by pranjalchanda08** [comment]
@deveshshevde, rebase dev after this merge. You may face conflicts. Have taken care of the warnings that you saw in your machine.

**Pull request merged**
